f = open("insiemi.csv")
S1 = set()
S2 = set()
for line in f:
    s1, s2 = line.strip("\n").split(",")
    s1, s2 = int(s1), int(s2)
    S1.add(s1)
    S2.add(s2)
f.close()

print("S1 contiene", len(S1), "elementi:", S1)
print("S2 contiene", len(S2), "elementi:", S2)
print("")
print("S1 ∩ S2 =", S1 & S2)
print("|S1 ∩ S2| =", len(S1 & S2))
print("")
print("S1 ∪ S2 =", S1 | S2)
print("|S1 ∪ S2| =", len(S1 | S2))
print("")
print("S1 - S2 =", S1 - S2)
print("|S1 - S2| =", len(S1 - S2))
print("")
print("S2 - S1 =", S2 - S1)
print("|S2 - S1| =", len(S2 - S1))
